### PR TITLE
Added CamelCase, kebab-case, and snake_case operations (and more)

### PR DESCRIPTION
**Pull request by blizzrdof77**
- Added CamelCase, kebab-case, and snake_case options
- Updated/Removed Icons
- Added keybinding for text selection transformation
- Added additional keywords "tt" and "transform" to default workflow options

### CODE REVIEW

**Comment by blizzrdof77** [comment]
@gillibrand - You still an active developer?

**Comment by gillibrand** [comment]
Sorry for ignoring you. I generally prefer Launchbar, so haven’t used Alfred or this extension in a long time.

I would have just pulled in your changes, but I really prefer the old icons that match the transformation you’re calling. If you can provide icons in the same style I’ll take another look at your changes.

**Comment by blizzrdof77** [comment]
@gillibrand - Updated the icons (as well as the icons.acorn file) and screenshot to match original style.

**Comment by gillibrand** [comment]
Thanks, I pulled this with a few tweaks. Notably, I removed the default hotkey since it immediately conflicted with something else I had (using "hyper key" convention of all modifiers http://brettterpstra.com/2012/12/08/a-useful-caps-lock-key/). I figure you can add that yourself if you use it--picking global hotkeys is always tricky.

**Comment by blizzrdof77** [comment]
Ah. My bad. I think I made a few modifications over the years that I've been using this workflow that I had forgotten about when I actually decided to contribute to the repo 🙈. Thanks for the merge though!

**Pull request merged**
